modLoader="javafml"
loaderVersion="[${forgeMinMajorForgeVersion},)"
license="All rights reserved"

[[mods]]
modId="lucky"
version="${forgeModVersion}"
displayName="Lucky Block"
authors="Alex Socha"
description="Adds a block with random outcomes"

[[dependencies.lucky]]
    modId="forge"
    mandatory=true
    versionRange="[${forgeMinMajorForgeVersion},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lucky]]
    modId="minecraft"
    mandatory=true
    versionRange="[${forgeMinMCVersion},)"
    ordering="NONE"
    side="BOTH"
